import type { Config } from 'tailwindcss'

// Design tokens ported 1:1 from the Stitch export's
// devyora_hooks_design_system/DESIGN.md and the inline
// tailwind.config script shared by every exported screen.
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#7f2b00',
        'on-secondary-container': '#fffbff',
        'on-background': '#131b2e',
        'inverse-primary': '#c3c0ff',
        'surface-container': '#eaedff',
        'secondary-fixed-dim': '#c0c1ff',
        'secondary-container': '#6063ee',
        'inverse-on-surface': '#eef0ff',
        'surface-tint': '#4d44e3',
        'on-primary-fixed-variant': '#3323cc',
        'on-primary-container': '#dad7ff',
        'error-container': '#ffdad6',
        'on-tertiary-fixed': '#370e00',
        'primary-container': '#4f46e5',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed-variant': '#2f2ebe',
        'on-primary': '#ffffff',
        'surface-dim': '#d2d9f4',
        'on-tertiary-container': '#ffd1c1',
        'surface-variant': '#dae2fd',
        'on-surface-variant': '#464555',
        outline: '#777587',
        background: '#faf8ff',
        secondary: '#4648d4',
        'tertiary-fixed-dim': '#ffb599',
        'on-primary-fixed': '#0f0069',
        'tertiary-container': '#aa3b00',
        'surface-container-lowest': '#ffffff',
        'surface-bright': '#faf8ff',
        'secondary-fixed': '#e1e0ff',
        'surface-container-low': '#f2f3ff',
        primary: '#3525cd',
        'primary-fixed-dim': '#c3c0ff',
        'on-surface': '#131b2e',
        'tertiary-fixed': '#ffdbce',
        'outline-variant': '#c7c4d8',
        tertiary: '#822c00',
        'surface-container-high': '#e2e7ff',
        'inverse-surface': '#283044',
        'primary-fixed': '#e2dfff',
        surface: '#faf8ff',
        'surface-container-highest': '#dae2fd',
        'on-error-container': '#93000a',
        'on-error': '#ffffff',
        error: '#ba1a1a',
        'on-secondary-fixed': '#07006c',
        'on-secondary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'gutter-mobile': '1rem',
        'margin-mobile': '1rem',
        margin: '2rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        gutter: '1.5rem',
      },
      fontFamily: {
        'display-mobile': ['Inter'],
        display: ['Inter'],
        'label-sm': ['Inter'],
        title: ['Inter'],
        'headline-md': ['Inter'],
        'headline-sm': ['Inter'],
        'headline-lg': ['Inter'],
        'label-md': ['Inter'],
        'body-sm': ['Inter'],
        'body-lg': ['Inter'],
        code: ['JetBrains Mono'],
        'headline-lg-mobile': ['Inter'],
        'body-md': ['Inter'],
      },
      fontSize: {
        'display-mobile': [
          '36px',
          { lineHeight: '44px', letterSpacing: '-0.025em', fontWeight: '700' },
        ],
        display: [
          '48px',
          { lineHeight: '56px', letterSpacing: '-0.03em', fontWeight: '700' },
        ],
        'label-sm': [
          '11px',
          { lineHeight: '14px', letterSpacing: '0.03em', fontWeight: '600' },
        ],
        title: [
          '16px',
          { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        'headline-md': [
          '24px',
          { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' },
        ],
        'headline-sm': [
          '20px',
          { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        'headline-lg': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' },
        ],
        'label-md': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' },
        ],
        'body-sm': [
          '13px',
          { lineHeight: '18px', letterSpacing: '0.005em', fontWeight: '400' },
        ],
        'body-lg': [
          '16px',
          { lineHeight: '26px', letterSpacing: '-0.005em', fontWeight: '400' },
        ],
        code: [
          '13px',
          { lineHeight: '20px', letterSpacing: '-0.01em', fontWeight: '500' },
        ],
        'headline-lg-mobile': [
          '26px',
          { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' },
        ],
        'body-md': [
          '14px',
          { lineHeight: '22px', letterSpacing: '0em', fontWeight: '400' },
        ],
      },
    },
  },
  plugins: [],
} satisfies Config
