import { createWriteStream } from 'node:fs'
import { mkdir, unlink, stat } from 'node:fs/promises'
import { createReadStream } from 'node:fs'
import path from 'node:path'
import { randomUUID } from 'node:crypto'
import { pipeline } from 'node:stream/promises'
import type { Readable } from 'node:stream'
import { env } from '../config/env.js'

/**
 * Storage provider abstraction — Chunk 2 blueprint §8: "do not create a
 * second storage system unnecessarily." Every caller in this codebase
 * talks to `StorageProvider`, never to the filesystem directly, so
 * swapping in an S3-compatible provider later (production) is a one-file
 * change here, not a rewrite of every route that uploads a file.
 *
 * This chunk ships only `LocalDiskStorageProvider` — there's no real S3
 * bucket available yet, and standing one up isn't needed to build the
 * ingestion/CRUD layer this chunk is scoped to. `getUploadUrl` is the
 * extension point a presigned-URL S3 provider would implement instead of
 * `saveStream`; local disk has no equivalent of a presigned PUT, so the
 * upload route below accepts a direct multipart stream instead for now.
 */
export interface StorageProvider {
  saveStream(params: {
    workspaceId: string
    filename: string
    stream: Readable
  }): Promise<{ storageKey: string; fileSizeBytes: number }>
  readStream(storageKey: string): Readable
  delete(storageKey: string): Promise<void>
}

function sanitizeFilename(filename: string): string {
  const base = path.basename(filename).replace(/[^a-zA-Z0-9._-]/g, '_')
  return base.length > 0 ? base : 'file'
}

export class LocalDiskStorageProvider implements StorageProvider {
  constructor(private readonly root: string) {}

  private absolutePath(storageKey: string): string {
    // storageKey is always generated by this class (never client input), so
    // there's no path-traversal surface — but resolve+contain anyway as a
    // defense-in-depth guard against a future caller passing one through.
    const resolved = path.resolve(this.root, storageKey)
    if (!resolved.startsWith(path.resolve(this.root))) {
      throw new Error('Invalid storage key')
    }
    return resolved
  }

  async saveStream(params: { workspaceId: string; filename: string; stream: Readable }) {
    const assetId = randomUUID()
    const safeName = sanitizeFilename(params.filename)
    const storageKey = `${params.workspaceId}/${assetId}/${safeName}`
    const destination = this.absolutePath(storageKey)

    await mkdir(path.dirname(destination), { recursive: true })
    await pipeline(params.stream, createWriteStream(destination))

    const { size } = await stat(destination)
    return { storageKey, fileSizeBytes: size }
  }

  readStream(storageKey: string): Readable {
    return createReadStream(this.absolutePath(storageKey))
  }

  async delete(storageKey: string): Promise<void> {
    await unlink(this.absolutePath(storageKey)).catch(() => {
      // Already gone — deleting a missing file is not an error here.
    })
  }
}

export const storage: StorageProvider = new LocalDiskStorageProvider(env.LOCAL_STORAGE_ROOT)
